나이브 베이지안은 범주형 변수 X를 사용하는 경우가 많다.

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

clf = GaussianNB()

clf.fit(features_train, labels_train)
pred = clf.predict(features_test)
accuracy = accuracy_score(pred, test)

print("score using accuracy: ",accuracy)

In [3]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
play_tennis = pd.read_csv('PlayTennis.csv')
play_tennis

Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [5]:
number = LabelEncoder() # Sunny를 2로 바꿔주거나 그런식으로 숫자로 바꿔주는 함수
play_tennis['Outlook'] = number.fit_transform(play_tennis['Outlook'])
play_tennis['Temperature'] = number.fit_transform(play_tennis['Temperature'])
play_tennis['Humidity'] = number.fit_transform(play_tennis['Humidity'])
play_tennis['Wind'] = number.fit_transform(play_tennis['Wind'])
play_tennis['Play Tennis'] = number.fit_transform(play_tennis['Play Tennis'])

play_tennis

Outlook  Temperature  Humidity  Wind  Play Tennis
0         2            1         0     1            0
1         2            1         0     0            0
2         0            1         0     1            1
3         1            2         0     1            1
4         1            0         1     1            1
5         1            0         1     0            0
6         0            0         1     0            1
7         2            2         0     1            0
8         2            0         1     1            1
9         1            2         1     1            1
10        2            2         1     0            1
11        0            2         0     0            1
12        0            1         1     1            1
13        1            2         0     0            0

In [6]:
features = ['Outlook','Temperature','Humidity','Wind']
target = 'Play Tennis'

X = play_tennis[features]
y = play_tennis[target]

print(X, y)

    Outlook  Temperature  Humidity  Wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0 0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play Tennis, dtype: int32


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
pred = model.predict(X_test)
accuracy = accuracy_score(y_test, pred)

print("acc : ",accuracy)

acc :  0.6


In [9]:
print(model.predict([[0,1,1,0]]))

[1]


In [11]:
from sklearn import datasets
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()
print(type(iris))

print('data shape: ', iris.data.shape)
print('iris target: ', iris.target_names)
print('iris features: ', iris.feature_names)

X = iris.data
print('type X: ', type(X))
print(X[:5])
y = iris.target
print('type y: ',type(y))
print(y[:5])

<class 'sklearn.utils.Bunch'>
data shape:  (150, 4)
iris target:  ['setosa' 'versicolor' 'virginica']
iris features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
type X:  <class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
type y:  <class 'numpy.ndarray'>
[0 0 0 0 0]


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = StandardScaler() #과적합방지, 연산속도향상
scaler.fit(X_train, y_train)
X_train_scale = scaler.transform(X_train)
X_test_scale = scaler.transform(X_test)

print(X_train_scale)
print(X_test_scale)

[[-0.98879974  0.81179441 -1.27510748 -1.30166929]
 [-0.8637671  -1.24145608 -0.40340468 -0.08767721]
 [-0.8637671   1.03993335 -1.333221   -1.30166929]
 [-1.11383237  0.12737758 -1.27510748 -1.4365573 ]
 [-0.36363657  1.03993335 -1.39133452 -1.30166929]
 [ 0.51159186 -1.92587292  0.46829811  0.45187483]
 [ 1.38682028  0.12737758  0.70075219  0.45187483]
 [-1.6139629  -1.69773397 -1.39133452 -1.16678128]
 [ 0.38655922 -0.55703925  0.17773051  0.18209881]
 [-1.36389763  0.35551652 -1.21699396 -1.30166929]
 [-0.23860394 -0.32890031 -0.05472356  0.18209881]
 [-1.238865   -0.10076137 -1.333221   -1.4365573 ]
 [ 0.88668975 -0.10076137  0.87509275  1.12631488]
 [-1.238865   -0.10076137 -1.333221   -1.16678128]
 [ 0.88668975 -0.55703925  0.52641163  0.45187483]
 [-1.11383237 -1.24145608  0.46829811  0.72165085]
 [ 0.63662449  0.58365546  1.34000091  1.80075492]
 [ 0.01146132 -1.01331714  0.17773051  0.0472108 ]
 [-1.48893027  0.81179441 -1.333221   -1.16678128]
 [ 0.13649396 -0.10076137  0.81

In [13]:
gnb = GaussianNB()
gnb.fit(X_train_scale, y_train)
y_pred = gnb.predict(X_test_scale)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  5  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91         5
           2       1.00      0.93      0.97        15

    accuracy                           0.97        30
   macro avg       0.94      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



In [14]:
from sklearn import datasets

wine = datasets.load_wine()

In [15]:
print("Features: ", wine.feature_names)
print("Labels: ",wine.target_names)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']


In [16]:
X = wine.data
y = wine.target

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

from sklearn import metrics

print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.9814814814814815


In [22]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(gnb,X,y,cv=5,scoring='accuracy')
print(scores)
print(scores.mean())

[0.94444444 0.97222222 0.97222222 0.94285714 1.        ]
0.9663492063492063
