In [1]:
# 배열타입의 데이터 생성
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr1_1 = np.array([10,20,30,40,50], dtype='float32')
arr1_2 = arr1_1.astype('int32')

arr2 = np.array([[1,2,3,4,5],[10,5,3,8,6],[9,6,11,4,2]])

arr3 = np.arange(0,10,2)
arr4 = np.arange(12).reshape(3,4) # reshape(3,4) : 3행4열
arr5 = np.linspace(1,10,5)
# linspace(start, end, num) : start와 end사이의 등간격으로 생성해서 num조각 냄. num 생략시 디폴트는 1
arr6 = np.linspace(0,np.pi,5)

print(arr1.dtype, arr1.ndim, arr1.strides, arr1.shape)

int32 1 (4,) (5,)


In [2]:
print(arr3, arr4, arr5, arr6)

[0 2 4 6 8] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [ 1.    3.25  5.5   7.75 10.  ] [0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [3]:
arr1 = np.arange(1,10)
print(arr1)
print(arr1[2], arr1[[2,4,6]])

arr2 = arr1.reshape(3,3).copy() # 깊은복사
arr2[1,1] = 10
print(arr2)
print(arr2[2][1],arr2[[0,1,2],[1,1,1]])
print(arr2[1:])
print(arr2[1:2,0:3])
print(arr2.tolist())

[1 2 3 4 5 6 7 8 9]
3 [3 5 7]
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
8 [ 2 10  8]
[[ 4 10  6]
 [ 7  8  9]]
[[ 4 10  6]]
[[1, 2, 3], [4, 10, 6], [7, 8, 9]]


# where()

for loop & if 보다 속도가 빠르다. 

조건에 맞는 값의 인덱스를 뽑아주거나, 조건에 맞는 값을 다른 값으로 대체하는 함수.

In [8]:
arr1 = np.array([10,30,50,20,80,40,50])
print(arr1.min(), np.min(arr1))
print(arr1.max(), np.max(arr1))
print(arr1.argmin(), np.argmin(arr1), arr1.argmax(), np.argmax(arr1)) # argmin(), argmax() : output이 인덱스
result = np.where(arr1>50)
print(result, type(result))
print(result[0])
print(result[0][0])

result = arr1[np.where(arr1>50)]
print(result)

print(np.where(arr1>50, 15, arr1)) # 이러면 arr1에 결과반영x == 15로 바뀌지x
result = np.where(arr1>50, 15, arr1)
print(result, arr1)

10 10
80 80
0 0 4 4
(array([4], dtype=int64),) <class 'tuple'>
[4]
4
[80]
[10 30 50 20 15 40 50]
[10 30 50 20 15 40 50] [10 30 50 20 80 40 50]


In [9]:
import pandas as pd
dic1 = {'a':20, 'b':40, 'c':30, 'd':60, 'e':70}
sr = pd.Series(dic1)
print(sr.index, sr.values)

lit1 = ['2020-08-19','analysis',9,True]
sr = pd.Series(lit1)
print(sr.index, sr.values)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') [20 40 30 60 70]
RangeIndex(start=0, stop=4, step=1) ['2020-08-19' 'analysis' 9 True]


In [10]:
sr = pd.Series(lit1, index=['a','b','c','d'])
# sr.index = ['aa','bb','cc','dd']
select1 = sr[[0,1]]
select2 = sr[0]
print(type(select1), type(select2))
print(select1)
print(select1.values)
print(select2)

<class 'pandas.core.series.Series'> <class 'str'>
a    2020-08-19
b      analysis
dtype: object
['2020-08-19' 'analysis']
2020-08-19


In [11]:
print(sr[1:3]) # 자동index 사용하는 경우, end값 포함되지 않는다.
print(sr['b':'d']) # 사용자가 직접 부여한 index 사용하는 경우, end값까지 포함된다.(데이터프레임에서도 동일하게 작용)

b    analysis
c           9
dtype: object
b    analysis
c           9
d        True
dtype: object


In [12]:
from IPython.display import display

dic1 = {'seoul':[100,300,250], 'pusan':[120,220,180], 'incheon':[90,250,170]}
df1 = pd.DataFrame(dic1)
# display(df1)
df1.index = ['apple','pear','mandarin']
# display(df1)
df2 = pd.DataFrame(df1, copy=True, dtype=np.float)
df2.rename(index={'apple':'water_melon'},inplace=True)
df1['seoul']['apple'] = 10
display(df1,df2)

# row 제거
df2.drop('water_melon', inplace=True) # axis = 0이 디폴트(row일 때 axis=0 // column일 때 axis=1)
display(df2)

seoul  pusan  incheon
apple        10    120       90
pear        300    220      250
mandarin    250    180      170

seoul  pusan  incheon
water_melon  100.0  120.0     90.0
pear         300.0  220.0    250.0
mandarin     250.0  180.0    170.0

seoul  pusan  incheon
pear      300.0  220.0    250.0
mandarin  250.0  180.0    170.0

In [14]:
# column 제거
df2.drop('seoul', inplace=True, axis=1)
display(df2)

pusan  incheon
pear      220.0    250.0
mandarin  180.0    170.0

In [16]:
display(df1['seoul'])
display(df1.seoul)
print()
print(df1[['seoul']])
#seoul의 apple값 확인
display(df1.seoul['apple'])
display(df1['seoul']['apple'])
display(df1['seoul'][0])
display(df1.loc['apple','seoul'])
display(df1.iloc[0,0])

#seoul의 apple,pear,mandarin 확인
display(df1.seoul[:3]) #df1['seoul'][:3]
display(df1.seoul[[0,1,2]])
display(df1.seoul['apple':'mandarin'])

#seoul, pusan의 mandarin 확인
display(df1.loc['mandarin',['seoul','pusan']])

apple        10
pear        300
mandarin    250
Name: seoul, dtype: int64

apple        10
pear        300
mandarin    250
Name: seoul, dtype: int64


          seoul
apple        10
pear        300
mandarin    250


10

10

10

10

10

apple        10
pear        300
mandarin    250
Name: seoul, dtype: int64

apple        10
pear        300
mandarin    250
Name: seoul, dtype: int64

apple        10
pear        300
mandarin    250
Name: seoul, dtype: int64

seoul    250
pusan    180
Name: mandarin, dtype: int64

In [20]:
# pear의 seoul,pusan,incheon의 값
print(df1.loc['pear',['seoul','pusan','incheon']])
print(df1.iloc[1,[0,1,2]])
print(df1.iloc[1,:])

seoul      300
pusan      220
incheon    250
Name: pear, dtype: int64
seoul      300
pusan      220
incheon    250
Name: pear, dtype: int64
seoul      300
pusan      220
incheon    250
Name: pear, dtype: int64


In [23]:
# apple,pear,mandarin의 pusan,incheon의 값
print(df1.loc[['apple','pear','mandarin'],['pusan','incheon']])

          pusan  incheon
apple       120       90
pear        220      250
mandarin    180      170


In [24]:
dic1 = [[100,300,250], [120,220,180], [90,250,170]]
df1 = pd.DataFrame(dic1, columns=['seoul','pusan','incheon'], index=['apple','pear','mandarin'])
display(df1)

df1['gwangju'] = [90,310,150] # 열(column) 추가
display(df1)

df1.loc['grape'] = [280,250,180,200] # 행(row) 추가
df1.loc[2] = np.nan # 이 순간부터 int 타입이 float 타입으로 바뀐다.
# nan이 들어와도 int타입으로 유지를 하고 싶다 >> df1 = pd.DataFrame(dic1,columns=[],index=[], dtype=pd.Int32Dtype())
display(df1)

#값 변경
df1['seoul']['apple'] = 110
df1['pusan']['apple','pear'] = 130,240
display(df1)

df1.loc['mandarin','incheon'] = 150
df1.T # 전치

seoul  pusan  incheon
apple       100    300      250
pear        120    220      180
mandarin     90    250      170

seoul  pusan  incheon  gwangju
apple       100    300      250       90
pear        120    220      180      310
mandarin     90    250      170      150

seoul  pusan  incheon  gwangju
apple     100.0  300.0    250.0     90.0
pear      120.0  220.0    180.0    310.0
mandarin   90.0  250.0    170.0    150.0
grape     280.0  250.0    180.0    200.0
2           NaN    NaN      NaN      NaN

seoul  pusan  incheon  gwangju
apple     110.0  130.0    250.0     90.0
pear      120.0  240.0    180.0    310.0
mandarin   90.0  250.0    170.0    150.0
grape     280.0  250.0    180.0    200.0
2           NaN    NaN      NaN      NaN

apple   pear  mandarin  grape   2
seoul    110.0  120.0      90.0  280.0 NaN
pusan    130.0  240.0     250.0  250.0 NaN
incheon  250.0  180.0     150.0  180.0 NaN
gwangju   90.0  310.0     150.0  200.0 NaN

In [25]:
new_df1 = df1.set_index(['seoul'])
display(new_df1)
new_df1.loc[110.0]

pusan  incheon  gwangju
seoul                         
110.0  130.0    250.0     90.0
120.0  240.0    180.0    310.0
90.0   250.0    150.0    150.0
280.0  250.0    180.0    200.0
NaN      NaN      NaN      NaN

pusan      130.0
incheon    250.0
gwangju     90.0
Name: 110.0, dtype: float64

In [26]:
date_index = pd.date_range('8/15/2020', periods=5, freq='D')
df1 = pd.DataFrame([100,np.nan,80,230,100],columns=['prices'],index=date_index)
display(df1)

date_index2 = pd.date_range('8/13/2020', periods=8, freq='D')
df2 = df1.reindex(date_index2) #df1.reindex(index=date_index2),(columns=date_index)
display(df2)

df2 = df1.reindex(date_index2, method='bfill') #(date_index2, fill_value=0)
display(df2)
df2.fillna(0)

prices
2020-08-15   100.0
2020-08-16     NaN
2020-08-17    80.0
2020-08-18   230.0
2020-08-19   100.0

prices
2020-08-13     NaN
2020-08-14     NaN
2020-08-15   100.0
2020-08-16     NaN
2020-08-17    80.0
2020-08-18   230.0
2020-08-19   100.0
2020-08-20     NaN

prices
2020-08-13   100.0
2020-08-14   100.0
2020-08-15   100.0
2020-08-16     NaN
2020-08-17    80.0
2020-08-18   230.0
2020-08-19   100.0
2020-08-20     NaN

prices
2020-08-13   100.0
2020-08-14   100.0
2020-08-15   100.0
2020-08-16     0.0
2020-08-17    80.0
2020-08-18   230.0
2020-08-19   100.0
2020-08-20     0.0

In [27]:
df = pd.DataFrame({'month':[1,3,5,7,9,11],
                  'year':['2015','2016','2017','2018','2019','2020'],
                  'sale':[300,400,200,450,500,350]})
new_df = df.set_index('month')
display(new_df)
new_df1 = new_df.reset_index()
display(new_df1)

#행 인덱스를 기준으로 해서 데이터프레임 정렬
sort_df1 = new_df1.sort_index(ascending=False)
display(sort_df1)

#특정열 데이터값을 기준으로 해서 데이터프레임 정렬
sort_value_df1 = new_df1.sort_values(by='sale',ascending=True)
display(sort_value_df1)

year  sale
month            
1      2015   300
3      2016   400
5      2017   200
7      2018   450
9      2019   500
11     2020   350

month  year  sale
0      1  2015   300
1      3  2016   400
2      5  2017   200
3      7  2018   450
4      9  2019   500
5     11  2020   350

month  year  sale
5     11  2020   350
4      9  2019   500
3      7  2018   450
2      5  2017   200
1      3  2016   400
0      1  2015   300

month  year  sale
2      5  2017   200
0      1  2015   300
5     11  2020   350
1      3  2016   400
3      7  2018   450
4      9  2019   500

In [1]:
import pandas as pd
from IPython.display import display

df1 = pd.read_excel('./stock price.xlsx')
df2 = pd.read_excel('./stock valuation.xlsx')
display(df1)
display(df2)

id stock_name          value   price
0  128940       한미약품   59385.666667  421000
1  130960     CJ E&M   58540.666667   98900
2  138250      엔에스쇼핑   14558.666667   13200
3  139480        이마트  239230.833333  254500
4  142280     녹십자엠에스     468.833333   10200
5  145990        삼양사   82750.000000   82000
6  185750        종근당   40293.666667  100500
7  192400      쿠쿠홀딩스  179204.666667  177500
8  199800         툴젠   -2514.333333  115400
9  204210     모두투어리츠    3093.333333    3475

id       name           eps     bps        per       pbr
0  130960     CJ E&M   6301.333333   54068  15.695091  1.829178
1  136480         하림    274.166667    3551  11.489362  0.887074
2  138040    메리츠금융지주   2122.333333   14894   6.313806  0.899691
3  139480        이마트  18268.166667  295780  13.931338  0.860437
4  145990        삼양사   5741.000000  108090  14.283226  0.758627
5  161390      한국타이어   5648.500000   51341   7.453306  0.820007
6  181710  NHN엔터테인먼트   2110.166667   78434  30.755864  0.827447
7  185750        종근당   3990.333333   40684  25.185866  2.470259
8  204210     모두투어리츠     85.166667    5335  40.802348  0.651359
9  207940   삼성바이오로직스   4644.166667   60099  89.790059  6.938551

In [ ]:
# eps: 주당순이익, bps: 주당순자산가치(기업순자산/발행주식수)
# per: 주가수익비율(현재주가/eps), pbr: 주가순자산비율(현재주가/pbs)

In [2]:
merge_inner = pd.merge(df1,df2)
display(merge_inner)

id stock_name          value   price    name           eps     bps  \
0  130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
1  139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
2  145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
3  185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
4  204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

         per       pbr  
0  15.695091  1.829178  
1  13.931338  0.860437  
2  14.283226  0.758627  
3  25.185866  2.470259  
4  40.802348  0.651359

In [3]:
# 데이터프레임 합치기 - 합집합
merge_outer = pd.merge(df1, df2, how='outer', on='id')
display(merge_outer)
print()

# 데이터프레임 합치기 - 왼쪽데이터프레임 기준, 키 값 분리
merge_left = pd.merge(df1, df2, how='left', left_on='stock_name', right_on='name')
display(merge_left)
print()

# 데이터프레임 합치기 - 오른쪽 데이터프레임 기준, 키 값 분리
merge_right = pd.merge(df1, df2, how='right', left_on='stock_name', right_on='name')
display(merge_left)
print()

id stock_name          value     price       name           eps  \
0   128940       한미약품   59385.666667  421000.0        NaN           NaN   
1   130960     CJ E&M   58540.666667   98900.0     CJ E&M   6301.333333   
2   138250      엔에스쇼핑   14558.666667   13200.0        NaN           NaN   
3   139480        이마트  239230.833333  254500.0        이마트  18268.166667   
4   142280     녹십자엠에스     468.833333   10200.0        NaN           NaN   
5   145990        삼양사   82750.000000   82000.0        삼양사   5741.000000   
6   185750        종근당   40293.666667  100500.0        종근당   3990.333333   
7   192400      쿠쿠홀딩스  179204.666667  177500.0        NaN           NaN   
8   199800         툴젠   -2514.333333  115400.0        NaN           NaN   
9   204210     모두투어리츠    3093.333333    3475.0     모두투어리츠     85.166667   
10  136480        NaN            NaN       NaN         하림    274.166667   
11  138040        NaN            NaN       NaN    메리츠금융지주   2122.333333   
12  161390        NaN            NaN       NaN      한국타이어   5648.500000   
13  181710        NaN            NaN       NaN  NHN엔터테인먼트   2110.166667   
14  207940        NaN            NaN       NaN   삼성바이오로직스   4644.166667   

         bps        per       pbr  
0        NaN        NaN       NaN  
1    54068.0  15.695091  1.829178  
2        NaN        NaN       NaN  
3   295780.0  13.931338  0.860437  
4        NaN        NaN       NaN  
5   108090.0  14.283226  0.758627  
6    40684.0  25.185866  2.470259  
7        NaN        NaN       NaN  
8        NaN        NaN       NaN  
9     5335.0  40.802348  0.651359  
10    3551.0  11.489362  0.887074  
11   14894.0   6.313806  0.899691  
12   51341.0   7.453306  0.820007  
13   78434.0  30.755864  0.827447  
14   60099.0  89.790059  6.938551

id_x stock_name          value   price      id_y    name           eps  \
0  128940       한미약품   59385.666667  421000       NaN     NaN           NaN   
1  130960     CJ E&M   58540.666667   98900  130960.0  CJ E&M   6301.333333   
2  138250      엔에스쇼핑   14558.666667   13200       NaN     NaN           NaN   
3  139480        이마트  239230.833333  254500  139480.0     이마트  18268.166667   
4  142280     녹십자엠에스     468.833333   10200       NaN     NaN           NaN   
5  145990        삼양사   82750.000000   82000  145990.0     삼양사   5741.000000   
6  185750        종근당   40293.666667  100500  185750.0     종근당   3990.333333   
7  192400      쿠쿠홀딩스  179204.666667  177500       NaN     NaN           NaN   
8  199800         툴젠   -2514.333333  115400       NaN     NaN           NaN   
9  204210     모두투어리츠    3093.333333    3475  204210.0  모두투어리츠     85.166667   

        bps        per       pbr  
0       NaN        NaN       NaN  
1   54068.0  15.695091  1.829178  
2       NaN        NaN       NaN  
3  295780.0  13.931338  0.860437  
4       NaN        NaN       NaN  
5  108090.0  14.283226  0.758627  
6   40684.0  25.185866  2.470259  
7       NaN        NaN       NaN  
8       NaN        NaN       NaN  
9    5335.0  40.802348  0.651359

id_x stock_name          value   price      id_y    name           eps  \
0  128940       한미약품   59385.666667  421000       NaN     NaN           NaN   
1  130960     CJ E&M   58540.666667   98900  130960.0  CJ E&M   6301.333333   
2  138250      엔에스쇼핑   14558.666667   13200       NaN     NaN           NaN   
3  139480        이마트  239230.833333  254500  139480.0     이마트  18268.166667   
4  142280     녹십자엠에스     468.833333   10200       NaN     NaN           NaN   
5  145990        삼양사   82750.000000   82000  145990.0     삼양사   5741.000000   
6  185750        종근당   40293.666667  100500  185750.0     종근당   3990.333333   
7  192400      쿠쿠홀딩스  179204.666667  177500       NaN     NaN           NaN   
8  199800         툴젠   -2514.333333  115400       NaN     NaN           NaN   
9  204210     모두투어리츠    3093.333333    3475  204210.0  모두투어리츠     85.166667   

        bps        per       pbr  
0       NaN        NaN       NaN  
1   54068.0  15.695091  1.829178  
2       NaN        NaN       NaN  
3  295780.0  13.931338  0.860437  
4       NaN        NaN       NaN  
5  108090.0  14.283226  0.758627  
6   40684.0  25.185866  2.470259  
7       NaN        NaN       NaN  
8       NaN        NaN       NaN  
9    5335.0  40.802348  0.651359

In [4]:
# 불린 인덱싱과 결합하여 원하는 데이터 찾기
price = df1[df1['price'] < 50000]
display(price.head())
print()

value = pd.merge(price,df2)
display(value)

id stock_name         value  price
2  138250      엔에스쇼핑  14558.666667  13200
4  142280     녹십자엠에스    468.833333  10200
9  204210     모두투어리츠   3093.333333   3475

id stock_name        value  price    name        eps   bps        per  \
0  204210     모두투어리츠  3093.333333   3475  모두투어리츠  85.166667  5335  40.802348   

        pbr  
0  0.651359

In [5]:
# join을 써보자
# 행 인덱스를 기준으로 결합하므로 index_col의 속성을 통해 공통 인덱스를 정해줌
df1 = pd.read_excel('./stock price.xlsx', index_col='id')
df2 = pd.read_excel('./stock valuation.xlsx', index_col='id')

# 데이터프레임 결합
df3 = df1.join(df2)
display(df3)
print()

# 데이터프레임 결합
df4 = df1.join(df2, how='inner')
display(df4)

stock_name          value   price    name           eps       bps  \
id                                                                         
128940       한미약품   59385.666667  421000     NaN           NaN       NaN   
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068.0   
138250      엔에스쇼핑   14558.666667   13200     NaN           NaN       NaN   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780.0   
142280     녹십자엠에스     468.833333   10200     NaN           NaN       NaN   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090.0   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684.0   
192400      쿠쿠홀딩스  179204.666667  177500     NaN           NaN       NaN   
199800         툴젠   -2514.333333  115400     NaN           NaN       NaN   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335.0   

              per       pbr  
id                           
128940        NaN       NaN  
130960  15.695091  1.829178  
138250        NaN       NaN  
139480  13.931338  0.860437  
142280        NaN       NaN  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
192400        NaN       NaN  
199800        NaN       NaN  
204210  40.802348  0.651359

stock_name          value   price    name           eps     bps  \
id                                                                       
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
130960  15.695091  1.829178  
139480  13.931338  0.860437  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
204210  40.802348  0.651359

In [6]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex','class','fare','survived']]
display(df.head())

age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [10]:
# class열을 기준으로 분할
grouped = df.groupby(['class'])
print(grouped)

for key, group in grouped:
    print('*key: ', key)
    print('*number: ', len(group))
    display(group.head())

*key:  First
*number:  216


age     sex  class     fare  survived
1   38.0  female  First  71.2833         1
3   35.0  female  First  53.1000         1
6   54.0    male  First  51.8625         0
11  58.0  female  First  26.5500         1
23  28.0    male  First  35.5000         1

*key:  Second
*number:  184


age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
17   NaN    male  Second  13.0000         1
20  35.0    male  Second  26.0000         0
21  34.0    male  Second  13.0000         1

*key:  Third
*number:  491


age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
2  26.0  female  Third   7.9250         1
4  35.0    male  Third   8.0500         0
5   NaN    male  Third   8.4583         0
7   2.0    male  Third  21.0750         0

In [11]:
# 연산메소드 적용
average = grouped.mean()
min_ = grouped.min()
display(average)
display(min_)
print()

# 개별 그룹 선택하기
group3 = grouped.get_group('Third')
display(group3.head())

age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

age     sex  fare  survived
class                               
First   0.92  female   0.0         0
Second  0.67  female   0.0         0
Third   0.42  female   0.0         0

age     sex     fare  survived
0  22.0    male   7.2500         0
2  26.0  female   7.9250         1
4  35.0    male   8.0500         0
5   NaN    male   8.4583         0
7   2.0    male  21.0750         0

In [12]:
# class열, sex열을 기준으로 분할
grouped_two = df.groupby(['class','sex'])

# grouped_two 그룹 객체를 iteration으로 출력
for key, group in grouped_two:
    print('* key: ',key)
    print('* number: ',len(group))
    display(group.head())
    print()
    
# grouped_two 그룹 객체에 연산 메소드 적용
average_two = grouped_two.mean()
display(average_two)
print()
print(type(average_two))

# grouped_two 그룹 객체에서 개별 그룹 선택하기
group3f = grouped_two.get_group(('Third','female'))
display(group3f.head())

* key:  ('First', 'female')
* number:  94


age     sex  class      fare  survived
1   38.0  female  First   71.2833         1
3   35.0  female  First   53.1000         1
11  58.0  female  First   26.5500         1
31   NaN  female  First  146.5208         1
52  49.0  female  First   76.7292         1


* key:  ('First', 'male')
* number:  122


age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0
30  40.0  male  First   27.7208         0
34  28.0  male  First   82.1708         0


* key:  ('Second', 'female')
* number:  76


age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0
43   3.0  female  Second  41.5792         1
53  29.0  female  Second  26.0000         1


* key:  ('Second', 'male')
* number:  108


age   sex   class  fare  survived
17   NaN  male  Second  13.0         1
20  35.0  male  Second  26.0         0
21  34.0  male  Second  13.0         1
33  66.0  male  Second  10.5         0
70  32.0  male  Second  10.5         0


* key:  ('Third', 'female')
* number:  144


age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0


* key:  ('Third', 'male')
* number:  347


age   sex  class     fare  survived
0   22.0  male  Third   7.2500         0
4   35.0  male  Third   8.0500         0
5    NaN  male  Third   8.4583         0
7    2.0  male  Third  21.0750         0
12  20.0  male  Third   8.0500         0

age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


<class 'pandas.core.frame.DataFrame'>


age     sex  class     fare  survived
2   26.0  female  Third   7.9250         1
8   27.0  female  Third  11.1333         1
10   4.0  female  Third  16.7000         1
14  14.0  female  Third   7.8542         0
18  31.0  female  Third  18.0000         0

In [13]:
average_age = grouped_two.age.mean()
display(average_age)

class   sex   
First   female    34.611765
        male      41.281386
Second  female    28.722973
        male      30.740707
Third   female    21.750000
        male      26.507589
Name: age, dtype: float64

In [14]:
grouped = df.groupby(['class'])

# 각 그룹에 대한 모든 열의 표준편차를 집계하여 데이터프레임으로 반환
std_all = grouped.std()
print(std_all)
print()
print(type(std_all))
print()

# 각 그룹에 대한 fare 열의 표준편차를 집계하여 시리즈로 반환
std_fare = grouped.fare.std()
print(std_fare)
print()
print(type(std_fare))
print()

              age       fare  survived
class                                 
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

<class 'pandas.core.frame.DataFrame'>

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

<class 'pandas.core.series.Series'>



In [15]:
# 그룹 객체에 agg() 메소드 적용_ 사용자 정의 함수를 인수로 전달
def min_max(x):
    return x.max() - x.min()

# 각 그룹의 최대값과 최소값의 차이를 계산하여 그룹별로 집계
agg_minmax = grouped.agg(min_max)
print(agg_minmax.head())
print()

# 여러 함수를 각 열에 동일하게 적용하여 집계
agg_all = grouped.agg(['min','max'])
print(agg_all.head())
print()

# 각 열마다 다른 함수를 적용하여 집계
agg_sep = grouped.agg({'fare':['min','max'],'age':'mean'})
print(agg_sep.head())

          age      fare  survived
class                            
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1

         age           sex       fare           survived    
         min   max     min   max  min       max      min max
class                                                       
First   0.92  80.0  female  male  0.0  512.3292        0   1
Second  0.67  70.0  female  male  0.0   73.5000        0   1
Third   0.42  74.0  female  male  0.0   69.5500        0   1

       fare                  age
        min       max       mean
class                           
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620


In [16]:
# 그룹 객체에 filter 함수 적용
# class 열을 기준으로 분할
grouped = df.groupby(['class'])

# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
grouped_filter = grouped.filter(lambda x: len(x) >= 200)
display(grouped_filter.head())
print()
print(type(grouped_filter))

# age열의 평균이 30보다 작은 그룹만을 필터링하여 데이터프레임으로 반환
age_filter = grouped.filter(lambda x: x.age.mean() < 30)
display(age_filter.tail())
print()
print(type(age_filter))

# 30 이하의 평균 및 30 이하의 group을 성별로 다시 재그룹
print(age_filter.mean())
age_filter_sex = age_filter.groupby(['sex'])
display(age_filter_sex.mean())

age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


<class 'pandas.core.frame.DataFrame'>


age     sex   class    fare  survived
884  25.0    male   Third   7.050         0
885  39.0  female   Third  29.125         0
886  27.0    male  Second  13.000         0
888   NaN  female   Third  23.450         0
890  32.0    male   Third   7.750         0


<class 'pandas.core.frame.DataFrame'>
age         26.692708
fare        15.580055
survived     0.305185
dtype: float64


age       fare  survived
sex                                   
female  24.681818  18.140172  0.645455
male    27.698153  14.342196  0.140659

In [18]:
# 피벗 예
import pandas as pd
import seaborn as sns
from IPython.display import display

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex','class','fare','survived']]
display(df.head())
print()

# 행, 열, 값, 집계에 사용할 열을 1개씩 지정 - 평균 집계
pdf1 = pd.pivot_table(df,
                     index='class',
                     values='survived',
                     aggfunc='mean')
display(pdf1.head())

age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

survived
class           
First   0.629630
Second  0.472826
Third   0.242363

In [19]:
pdf1 = pd.pivot_table(df,
                     index='class',
                     columns='sex',
                     values='age',
                     aggfunc='mean')
display(pdf1.head())
print()

# 값에 적용하는 집계 함수를 2개 이상 지정 가능 - 생존율, 생존자 수 집계
pdf2 = pd.pivot_table(df,
                     index='class',
                     columns='sex',
                     values='survived',
                     aggfunc=['mean','sum'])
display(pdf2.head())

sex        female       male
class                       
First   34.611765  41.281386
Second  28.722973  30.740707
Third   21.750000  26.507589

mean              sum     
sex       female      male female male
class                                 
First   0.968085  0.368852     91   45
Second  0.921053  0.157407     70   17
Third   0.500000  0.135447     72   47

In [23]:
# 행, 열 값에 사용할 열을 2개 이상 지정 가능- 평균나이, 최대요금 집계
pdf3 = pd.pivot_table(df,
                     index=['class','sex'],
                     columns='survived',
                     values=['age','fare'],
                     aggfunc=['mean','max'])

# IPython Console 디스플레이 옵션 설정
pd.set_option('display.max_columns',10) #출력할 열의 개수 한도
display(pdf3.head())
print()

# 행, 열 구조 살펴보기
print(pdf3.index)
print(pdf3.columns)

mean                                      max        \
                     age                   fare               age         
survived               0          1           0           1     0     1   
class  sex                                                                
First  female  25.666667  34.939024  110.604167  105.978159  50.0  63.0   
       male    44.581967  36.248000   62.894910   74.637320  71.0  80.0   
Second female  36.000000  28.080882   18.250000   22.288989  57.0  55.0   
       male    33.369048  16.022000   19.488965   21.095100  70.0  62.0   
Third  female  23.818182  19.329787   19.773093   12.464526  48.0  63.0   

                                 
                 fare            
survived            0         1  
class  sex                       
First  female  151.55  512.3292  
       male    263.00  512.3292  
Second female   26.00   65.0000  
       male     73.50   39.0000  
Third  female   69.55   31.3875


MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ('Second',   'male'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])
MultiIndex([('mean',  'age', 0),
            ('mean',  'age', 1),
            ('mean', 'fare', 0),
            ('mean', 'fare', 1),
            ( 'max',  'age', 0),
            ( 'max',  'age', 1),
            ( 'max', 'fare', 0),
            ( 'max', 'fare', 1)],
           names=[None, None, 'survived'])


In [24]:
print(pdf3.xs('First'))
print(pdf3.xs(('First','female')))
print(pdf3.xs('male',level='sex'))
print(pdf3.xs(('Second','male'),level=[0,'sex']))

               mean                                      max                \
                age                   fare               age          fare   
survived          0          1           0           1     0     1       0   
sex                                                                          
female    25.666667  34.939024  110.604167  105.978159  50.0  63.0  151.55   
male      44.581967  36.248000   62.894910   74.637320  71.0  80.0  263.00   

                    
                    
survived         1  
sex                 
female    512.3292  
male      512.3292  
            survived
mean  age   0            25.666667
            1            34.939024
      fare  0           110.604167
            1           105.978159
max   age   0            50.000000
            1            63.000000
      fare  0           151.550000
            1           512.329200
Name: (First, female), dtype: float64
               mean                                    max        

In [26]:
print(pdf3.xs(('Second','male')))
print(pdf3.xs(('Second','male'),level=['class','sex']))

            survived
mean  age   0           33.369048
            1           16.022000
      fare  0           19.488965
            1           21.095100
max   age   0           70.000000
            1           62.000000
      fare  0           73.500000
            1           39.000000
Name: (Second, male), dtype: float64
                  mean                               max                  
                   age               fare            age        fare      
survived             0       1          0        1     0     1     0     1
class  sex                                                                
Second male  33.369048  16.022  19.488965  21.0951  70.0  62.0  73.5  39.0


In [28]:
import datetime
import numpy as np
import pandas as pd
np.random.seed(777)

df = pd.DataFrame({'A':['one','one','two','three']*6,
                  'B':['A','B','C']*8,
                  'C':['foo','foo','foo','bar','bar','bar']*4,
                  'D': np.random.randn(24),
                  'E': np.random.randn(24),
                  'F': [datetime.datetime(2013,i,1) for i in range(1,13)]
                  + [datetime.datetime(2013,i,15) for i in range(1,13)]})
display(df)

A  B    C         D         E          F
0     one  A  foo -0.468209  0.094700 2013-01-01
1     one  B  foo -0.822825 -1.542812 2013-02-01
2     two  C  foo -0.065380  2.479370 2013-03-01
3   three  A  bar -0.713362  0.456867 2013-04-01
4     one  B  bar  0.906351 -0.313873 2013-05-01
5     one  C  bar  0.766237  0.021037 2013-06-01
6     two  A  foo  0.826054  0.960793 2013-07-01
7   three  B  foo -1.323683  0.058483 2013-08-01
8     one  C  foo -1.752445 -0.446032 2013-09-01
9     one  A  bar  1.002449  0.319197 2013-10-01
10    two  B  bar  0.544809  0.841169 2013-11-01
11  three  C  bar  1.895161 -1.532762 2013-12-01
12    one  A  foo -0.769357 -0.281584 2013-01-15
13    one  B  foo -1.403096  1.744453 2013-02-15
14    two  C  foo -0.632468 -0.674239 2013-03-15
15  three  A  bar -0.558874  0.588401 2013-04-15
16    one  B  bar -1.233231  1.804363 2013-05-15
17    one  C  bar -0.439504  2.056250 2013-06-15
18    two  A  foo  0.914787  1.454582 2013-07-15
19  three  B  foo  0.265041 -0.138412 2013-08-15
20    one  C  foo -1.383370  0.342872 2013-09-15
21    one  A  bar  0.685512 -0.727618 2013-10-15
22    two  B  bar  0.456091 -1.403946 2013-11-15
23  three  C  bar -0.461374 -1.240611 2013-12-15

In [32]:
# one 클래스이면서 등급이 A이고 'foo'에 해당되는 D의 평균 및 합산은?
pdf = pd.pivot_table(df,
                     index=['A','B'],
                     columns='C',
                     values='D',
                     aggfunc=['mean','sum'])
display(pdf)

mean                 sum          
C             bar       foo       bar       foo
A     B                                        
one   A  0.843980 -0.618783  1.687961 -1.237566
      B -0.163440 -1.112960 -0.326880 -2.225921
      C  0.163367 -1.567907  0.326733 -3.135815
three A -0.636118       NaN -1.272236       NaN
      B       NaN -0.529321       NaN -1.058642
      C  0.716893       NaN  1.433787       NaN
two   A       NaN  0.870421       NaN  1.740841
      B  0.500450       NaN  1.000900       NaN
      C       NaN -0.348924       NaN -0.697848

In [34]:
# 타이타닉 데이터에서 승선한 지역의 이름을 중복없이 출력하고, 가장 빈도가 높은 지역은?
embark = titanic['embark_town'].unique()
embark_count = titanic['embark_town'].value_counts()
display(embark_count)
print(embark, embark_count.index[0])

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

['Southampton' 'Cherbourg' 'Queenstown' nan] Southampton


In [35]:
# Titanic에서 age, fare 컬럼에서 결측치를 확인하는 코드 작성
df = titanic.loc[:,['age','fare']]

def missing_value(data):
    return data.isnull()

missing_result = df.apply(missing_value, axis=0)
display(missing_result)
print(missing_result.sum())

age   fare
0    False  False
1    False  False
2    False  False
3    False  False
4    False  False
..     ...    ...
886  False  False
887  False  False
888   True  False
889  False  False
890  False  False

[891 rows x 2 columns]

age     177
fare      0
dtype: int64


In [36]:
# Titanic 전체에서 누락데이터 몇건이 있는지
def missing_value(data):
    return data.isnull().sum()

print(titanic.apply(missing_value))

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [37]:
# 타이타닉의 나이데이터의 결측치를 나이데이터의 중앙값으로 교체
df = titanic.loc[:,'survived':'class']
df['age'] = df['age'].fillna(df['age'].median())
print(df.apply(missing_value))

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
class       0
dtype: int64


In [38]:
# 위의 df에 저장된 타이타닉의 컬럼명을 abcd 순서대로 출력
columns = list(df.columns.values)
columns_sort = sorted(columns)
display(df[columns_sort])
df_sort = df[columns_sort]
df_sort

age   class embarked     fare  parch  pclass     sex  sibsp  survived
0    22.0   Third        S   7.2500      0       3    male      1         0
1    38.0   First        C  71.2833      0       1  female      1         1
2    26.0   Third        S   7.9250      0       3  female      0         1
3    35.0   First        S  53.1000      0       1  female      1         1
4    35.0   Third        S   8.0500      0       3    male      0         0
..    ...     ...      ...      ...    ...     ...     ...    ...       ...
886  27.0  Second        S  13.0000      0       2    male      0         0
887  19.0   First        S  30.0000      0       1  female      0         1
888  28.0   Third        S  23.4500      2       3  female      1         0
889  26.0   First        C  30.0000      0       1    male      0         1
890  32.0   Third        Q   7.7500      0       3    male      0         0

[891 rows x 9 columns]

age   class embarked     fare  parch  pclass     sex  sibsp  survived
0    22.0   Third        S   7.2500      0       3    male      1         0
1    38.0   First        C  71.2833      0       1  female      1         1
2    26.0   Third        S   7.9250      0       3  female      0         1
3    35.0   First        S  53.1000      0       1  female      1         1
4    35.0   Third        S   8.0500      0       3    male      0         0
..    ...     ...      ...      ...    ...     ...     ...    ...       ...
886  27.0  Second        S  13.0000      0       2    male      0         0
887  19.0   First        S  30.0000      0       1  female      0         1
888  28.0   Third        S  23.4500      2       3  female      1         0
889  26.0   First        C  30.0000      0       1    male      0         1
890  32.0   Third        Q   7.7500      0       3    male      0         0

[891 rows x 9 columns]